import React, { Component } from "react";
import { Link } from "react-router-dom";
import ReactDOM from "react-dom";

const game_abouts = {
  Conway: <div className="col-12">
    <p>
      The most well-known example of a cellular automata system
      is <a href="https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life">John Conway's game of Life</a>,
      a deterministic ruleset for two-dimensional grids in which cells can be alive or dead, and their
      living status at one timestep is based on their living status and total number of neighbors on
      the previous timestep.
    </p>
    <img src="/static/img/conway.gif"/>
    <p className="caption">Conway's original Game of Life</p>
    <p>
      Conway's ruleset stipulated that living cells with 2 or 3 neighbors should continue living, and dead
      cells with 3 neighbors should become alive. One can imagine the space of similar determinist rulesets -
      since grid cells can have 0 to 8 neighbors, there are 9 choices to make about when living cells stay
      alive, and 9 choices about when dead cells become alive, so that there is a total of 2<sup>18</sup> rulesets
      in this family.
    </p>
    <p>
      A further generalization is to make the rulesets probabilistic, so that a cell's number of neighbors determines
      the probability that it is alive on the next timestep. Like most of our rulesets on this site, the Conway
      rulesets we generate are "mostly deterministic" - skewed so that most generated rules specify that a cell
      with a particular number of neighbors almost always lives or almost always dies.
    </p>
    <img src="/static/img/probconway.gif"/>
    <p className="caption">An example of a probabilistic Conway ruleset generated by our model</p>
  </div>,

  RedVsBlue: <div className="col-12">
    rvb is kool
  </div>,

  Rhomdos: <div className="col-12">
    swiggity swooty
  </div>,
}

class About extends Component {
    render() {
      return(
        <div className="container constrained about">
          <div className="row">
            <div className="col-12">
              <p style={{textAlign: "center"}}>
                Want to help us out? <Link to={"/" + this.props.game_name + "/rate"}>Rate a few games!</Link>
                <br/>
                Our work is supported by volunteer image ratings, which give our machine learning model more data to
                become better!
              </p>
            </div>

            {game_abouts[this.props.game_name]}
          </div>
        </div>
      )

    }
}

export default About;